[package]
name = "linkbot-core"
version = "0.0.1"
authors = ["David Ko <david@barobo.com>"]
build = "build.rs"

[dependencies]
protobuf = "*"
log = "*"
rand = "*"

[build-dependencies]
protoc-rust = "*"
